CREATE TABLE usuario (
    userId INT PRIMARY KEY,
    userName VARCHAR (30) NOT NULL,
    userEmail TEXT NOT NULL,
    userSenha VARCHAR (30),
    userCargo VARCHAR (30)
);

INSERT INTO usuario (userId, userName, userEmail, userSenha, userCargo) VALUES
(1, 'Ana Silva', 'ana.silva@email.com', 'senha123', 'Administrador'),
(2, 'Bruno Costa', 'bruno.costa@email.com', 'abc123', 'Funcionário'),
(3, 'Carla Souza', 'carla.souza@email.com', 'carla321', 'Gerente'),
(4, 'Daniel Lima', 'daniel.lima@email.com', 'dan2024', 'Funcionário'),
(5, 'Eduarda Rocha', 'eduarda.rocha@email.com', 'edu456', 'Cliente'),
(6, 'Felipe Alves', 'felipe.alves@email.com', 'fel789', 'Funcionário'),
(7, 'Gabriela Martins', 'gabriela@email.com', 'gab123', 'Cliente'),
(8, 'Henrique Santos', 'henrique@email.com', 'hen456', 'Gerente'),
(9, 'Isabela Gomes', 'isabela@email.com', 'isa789', 'Cliente'),
(10, 'João Pereira', 'joao@email.com', 'joao321', 'Funcionário'),
(11, 'Karen Dias', 'karen@email.com', 'kar123', 'Cliente'),
(12, 'Lucas Oliveira', 'lucas@email.com', 'luc456', 'Funcionário'),
(13, 'Mariana Ribeiro', 'mariana@email.com', 'mar789', 'Administrador'),
(14, 'Nicolas Ferreira', 'nicolas@email.com', 'nic123', 'Funcionário'),
(15, 'Olivia Barbosa', 'olivia@email.com', 'oli456', 'Cliente'),
(16, 'Paulo Mendes', 'paulo@email.com', 'pau789', 'Gerente'),
(17, 'Quezia Almeida', 'quezia@email.com', 'que123', 'Cliente'),
(18, 'Rafael Cardoso', 'rafael@email.com', 'raf456', 'Funcionário'),
(19, 'Sabrina Castro', 'sabrina@email.com', 'sab789', 'Cliente'),
(20, 'Tiago Rodrigues', 'tiago@email.com', 'tia123', 'Funcionário'),
(21, 'Ursula Nunes', 'ursula@email.com', 'urs456', 'Cliente'),
(22, 'Vinicius Melo', 'vinicius@email.com', 'vin789', 'Administrador'),
(23, 'William Araujo', 'william@email.com', 'wil123', 'Funcionário'),
(24, 'Xavier Freitas', 'xavier@email.com', 'xav456', 'Gerente'),
(25, 'Yasmin Teixeira', 'yasmin@email.com', 'yas789', 'Cliente'),
(26, 'Zeca Moraes', 'zeca@email.com', 'zec123', 'Funcionário'),
(27, 'Amanda Lopes', 'amanda@email.com', 'ama456', 'Cliente'),
(28, 'Bernardo Pinto', 'bernardo@email.com', 'ber789', 'Funcionário'),
(29, 'Camila Farias', 'camila@email.com', 'cam123', 'Gerente'),
(30, 'Diego Correia', 'diego@email.com', 'die456', 'Funcionário'),
(31, 'Elaine Campos', 'elaine@email.com', 'ela789', 'Cliente'),
(32, 'Fernando Vieira', 'fernando@email.com', 'fer123', 'Funcionário'),
(33, 'Giovana Reis', 'giovana@email.com', 'gio456', 'Cliente'),
(34, 'Hugo Carvalho', 'hugo@email.com', 'hug789', 'Administrador'),
(35, 'Ingrid Monteiro', 'ingrid@email.com', 'ing123', 'Cliente'),
(36, 'José Ramos', 'jose@email.com', 'jos456', 'Funcionário'),
(37, 'Kelly Andrade', 'kelly@email.com', 'kel789', 'Cliente'),
(38, 'Leonardo Duarte', 'leonardo@email.com', 'leo123', 'Gerente'),
(39, 'Michele Rezende', 'michele@email.com', 'mic456', 'Funcionário'),
(40, 'Nathan Borges', 'nathan@email.com', 'nat789', 'Cliente'),
(41, 'Patricia Moreira', 'patricia@email.com', 'pat123', 'Funcionário'),
(42, 'Renato Cunha', 'renato@email.com', 'ren456', 'Administrador'),
(43, 'Simone Pires', 'simone@email.com', 'sim789', 'Cliente'),
(44, 'Tatiane Lopes', 'tatiane@email.com', 'tat123', 'Funcionário'),
(45, 'Valeria Fernandes', 'valeria@email.com', 'val456', 'Cliente'),
(46, 'Wesley Moura', 'wesley@email.com', 'wes789', 'Funcionário'),
(47, 'Yuri Bastos', 'yuri@email.com', 'yur123', 'Gerente'),
(48, 'Bianca Sales', 'bianca@email.com', 'bia456', 'Cliente'),
(49, 'Claudio Neves', 'claudio@email.com', 'cla789', 'Funcionário'),
(50, 'Debora Machado', 'debora@email.com', 'deb123', 'Administrador');

SELECT * FROM usuario

